# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fdf088d20fe19c66c2f951d7115242f796ae265b72b154067da2f5fe87e9175186479fae79caa152e99fd25f4e3d4bcd7c677bac812e7d79e552c7d122ec19e

test:
  secret_key_base: 9341912fd00dfda8013f3a51cda02a41e88a1deb0dd8d3cfbefbd39abdea26f452a0efc9a26a91ecea26ea44e208d4dd8b075b62db3fbe53141586ef59d9f7ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
